#!/bin/sh

#   WARNING   this file is automatically generated by RT-Druid

#   If you want modify this file, you should move it to a safe folder,
#   like the project's root, and update the path inside the project 
#   properties "C/C++ Make Project" -> "Build command"
#   i.e.   ${workspace_loc:Project_Hand_Coded}/make_launcher.bat


ERIKA_FILES=/Applications/eclipse/plugins/com.eu.evidence.ee_2.7.0.20160615_1643/ee_files
export ERIKA_FILES

make $@
